apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube
        ports:
        - containerPort: 9000
        env:
        - name: SONARQUBE_JDBC_URL
          value: "jdbc:postgresql://<db-host>:5432/sonarqube"
        - name: SONARQUBE_JDBC_USERNAME
          value: "<db-username>"
        - name: SONARQUBE_JDBC_PASSWORD
          value: "<db-password>"